version: '2'
services:
  site:
    build: .
    expose:
     - "5000"
    volumes:
     - ./:/var/www:ro
     - ${GALLERY}:/var/www/gallery
  nginx:
    image: nginx:alpine
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
     - ${GALLERY}:/media/
    ports:
     - "${FTIMG_PORT}:80"
